CREATE TABLE realty (
    offer_id BIGINT,
    date_parsed DATE,
    address_id INT,
    n_rooms INTEGER,
    is_studio BOOLEAN,
    area DECIMAL(5, 2),
    floor INTEGER,
    total_floors INTEGER,
    height DECIMAL(4, 2),
    construction_year INTEGER,
    has_pledge BOOLEAN,
    pledge INTEGER,
    commission_fee INTEGER,
    utilities VARCHAR(30),
    price INTEGER,
    latitude DECIMAL(8, 5),
    longitude DECIMAL(8, 5),
    has_furniture BOOLEAN,
    has_kitchen_furniture BOOLEAN,
    building_type VARCHAR(30),
    finishing_type VARCHAR(20),
    balcony_cnt INTEGER,
    loggia_cnt INTEGER,
    window_view_type VARCHAR(20),
    bathroom_type VARCHAR(20),
    parking_type VARCHAR(20),
    is_closed_area BOOLEAN,
    is_pet_available BOOLEAN,
    is_kid_available BOOLEAN,
    has_lift BOOLEAN,
    has_internet BOOLEAN,
    has_air_conditioner BOOLEAN,
    heating_type VARCHAR(20),
    has_garbage_chute BOOLEAN,
    has_security BOOLEAN,
    has_dishwasher BOOLEAN,
    has_alarm BOOLEAN,
    has_washing_machine BOOLEAN,
    has_tv BOOLEAN,
    has_fridge BOOLEAN,
    has_phone BOOLEAN,
    is_individual_project BOOLEAN,
    PRIMARY KEY (offer_id, date_parsed)
);